// Generates public/streamApiConfig.js from env or defaults
const fs = require('fs');
const path = require('path');

const OUTPUT = path.join(__dirname, '..', 'public', 'streamApiConfig.js');
const ENV_FILES = ['.env', '.env.local'];

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return {};
  const raw = fs.readFileSync(filePath, 'utf8');
  const out = {};
  raw.split(/\r?\n/).forEach((line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return;
    const eqIndex = trimmed.indexOf('=');
    if (eqIndex <= 0) return;
    const key = trimmed.slice(0, eqIndex).trim();
    let value = trimmed.slice(eqIndex + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  });
  return out;
}

const repoRoot = path.join(__dirname, '..');
const fileEnv = {};
ENV_FILES.forEach((name) => {
  Object.assign(fileEnv, parseEnvFile(path.join(repoRoot, name)));
});

const getEnv = (name, fallback = '') => {
  if (process.env[name] != null && process.env[name] !== '') return process.env[name];
  if (fileEnv[name] != null && fileEnv[name] !== '') return fileEnv[name];
  return fallback;
};

const STREAM_API = getEnv('STREAM_API', 'https://convinced-nara-personal122-7da52759.koyeb.app/api/v1');
const CONSUMET_API = getEnv('CONSUMET_API', 'https://api.consumet.org');
const TWOEMBED_API = getEnv('TWOEMBED_API', '');
const TMDB_API_KEY = getEnv('TMDB_API_KEY', '');
const YT_API_KEY = getEnv('YT_API_KEY', '');

const content = `// Auto-generated by scripts/generateStreamApiConfig.js
// Configure browser-safe runtime values here (generated from env).
window.CONSUMET_API = ${JSON.stringify(CONSUMET_API)};
window.STREAM_API = ${JSON.stringify(STREAM_API)};
window.TWOEMBED_API = ${JSON.stringify(TWOEMBED_API)};
window.TMDB_API_KEY = ${JSON.stringify(TMDB_API_KEY)};
window.YT_API_KEY = ${JSON.stringify(YT_API_KEY)};
console.log('[ok] Consumet API configured:', window.CONSUMET_API);
console.log('[ok] Stream API configured:', window.STREAM_API);
console.log('[ok] 2Embed API configured:', window.TWOEMBED_API || '(not configured)');
console.log('[ok] TMDB key configured:', Boolean(window.TMDB_API_KEY));
console.log('[ok] YouTube key configured:', Boolean(window.YT_API_KEY));
`;

fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
fs.writeFileSync(OUTPUT, content, 'utf8');
console.log(`[streamApiConfig] Wrote ${OUTPUT}`);
