// Generates public/streamApiConfig.js from env or defaults
const fs = require('fs');
const path = require('path');

const OUTPUT = path.join(__dirname, '..', 'public', 'streamApiConfig.js');

// Use your 8Stream backend by default (can be overridden with STREAM_API env var)
const STREAM_API = process.env.STREAM_API || 'https://convinced-nara-personal122-7da52759.koyeb.app/api/v1';

const content = `// Auto-generated by scripts/generateStreamApiConfig.js
// Configure your Stream API endpoint here
window.STREAM_API = '${STREAM_API}';
console.log('✓ Stream API configured:', window.STREAM_API);
`;

fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
fs.writeFileSync(OUTPUT, content, 'utf8');
console.log(`[streamApiConfig] Wrote ${OUTPUT} with STREAM_API=${STREAM_API}`);
